.PHONY: all

all: kyrie.gtex gloria.gtex sanctus.gtex agnus.gtex ite.gtex

kyrie.gtex:
	gregorio kyrie.gabc

gloria.gtex:
	gregorio gloria.gabc

sanctus.gtex:
	gregorio sanctus.gabc

agnus.gtex:
	gregorio agnus.gabc

ite.gtex:
	gregorio ite.gabc
