plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/exec":
      - "publishCmd": "make -j $(nproc)"
  - "@semantic-release/git"
  -
    - "@semantic-release/github"
    - "assets": ["pdfs/*.pdf"]




