plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/exec":
      - "publishCmd": "scripts/build.sh"
  - "@semantic-release/git"
  -
    - "@semantic-release/github"
    - "assets": ["pdfs/*.pdf"]




