# Changes here will be overwritten by Copier
_commit: 0.1.0-1-g3c5f03a
_src_path: /home/john/code/DominicanRiteTemplate
alleluia: alleluia
asperges: false
creator_name: John Morris
creed: 1
creed_path: ../DominicanOrdinaries/credo
feast_name: S. Andreæ Corsini Episcopi et Confessoris
gloria: true
img_file: ../img/logo.png
marian: true
mass_setting: 3
mass_type: Missa Cantata
masses_path: ../DominicanOrdinaries/masses
preface: standard
repo_url: https://github.com/2e0byo/StCuthbertsMasses
