# Changes here will be overwritten by Copier
_commit: v1.2.2
_src_path: gh:2e0byo/MassTemplate.git
alleluia: alleluia
asperges: false
creator_name: John Morris
creed: 1
creed_path: ../DominicanOrdinaries/credo
creedp: false
feast_name: S. Andreæ Corsini Episcopi et Confessoris
gloria: true
img_file: ../img/logo.png
marian: true
mass_setting: 3
mass_type: Missa Cantata
masses_path: ../DominicanOrdinaries/masses
preface: standard
repo_url: https://github.com/2e0byo/StCuthbertsMasses
rite: dominican
version: v1.0.0
