.PHONY: all

all: amen.gtex dominus_vobiscum.gtex pax_domini.gtex pref.gtex sed.gtex sequenti.gtex

amen.gtex:
	gregorio amen.gabc

dominus_vobiscum.gtex:
	gregorio dominus_vobiscum.gabc

pax_domini.gtex:
	gregorio pax_domini.gabc

pref.gtex:
	gregorio pref.gabc

sed.gtex:
	gregorio sed.gabc

sequenti.gtex:
	gregorio sequenti.gabc
