on:
  push:
    # Sequence of patterns matched against refs/tags
  pull_request:
  workflow_dispatch:

name: Build and upload artifact

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add git
            sh .git-hook
            apk add make

      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - run: yarn install
      - name: Semantic Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: Pdfs
          path: pdfs/*.pdf

