# Changes here will be overwritten by Copier
_commit: v2.1.1
_src_path: gh:2e0byo/MassTemplate
alleluia: alleluia
asperges: false
creator_name: John Morris
creed: null
creed_path: ../Ordinaries/credo
creedp: false
feast_name: S Mariæ Sabbato
gloria: true
img_file: ../img/logo.png
marian: true
mass_setting: 9
mass_type: Missa Cantata
masses_path: ../Ordinaries/masses
preface: standard
repo_url: https://github.com/2e0byo/StCuthbertsMasses
rite: roman
version: v1.0.0
